# Generated by Django 4.2.17 on 2024-12-11 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Estudiantes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("apellido", models.CharField(max_length=50)),
                ("correo", models.EmailField(max_length=254, unique=True)),
                ("edad", models.IntegerField()),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
